spring:
  profiles:
    active: local

server:
  port: 8082

---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://localhost:27017/log

app:
  rabbitmq:
    exchange: logger.exchange
    queue: logger.queue
    routing:
      pattern: logger.controller.#

---
spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://10.0.10.206:27017/log
      username: mruser
      password: qwer1234!

---
spring:
  profiles: prod
  devtools:
    livereload:
      enabled: true
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://10.0.10.206:27017/log
      username: mruser
      password: qwer1234!